name: Unity Workflow Sample
on: [push]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
         lfs: true
     - uses: actions/cache@v1.1.0
       with:
         path: ./Library
         key: Library

     - uses: webbertakken/unity-test-runner@v1.4
       with:
        unityVersion: 2019.1.5f1

     - uses: actions/upload-artifact@v1
       with:
        name: Test results
        path: artifacts

     - name: Build project
       uses: webbertakken/unity-builder@v2.0-alpha-6
       with:
         customImage: 'unityci/editor:2019.4.5f1-android-0.3.0'
         unityVersion: 2019.4.5f1
         targetPlatform: Android

     - uses: actions/upload-artifact@v1
       with:
         name: Build
         path: build
